---
  version: 2.1
  orbs:
    ruby: circleci/ruby@1.0.0
  jobs:
    build:
      docker:
        - image: circleci/ruby:2.7.0
          environment:
            RAILS_ENV: test
      steps:
        - checkout
        - ruby/install-deps
    analyze:
      docker:
        - image: circleci/ruby:2.7.0
          environment:
            RAILS_ENV: test
      steps:
        - checkout
        - ruby/install-deps
        - run: bundle exec rubocop
    test:
      docker:
        - image: circleci/ruby:2.7.0
          environment:
            RAILS_ENV: test
      steps:
        - checkout
        - ruby/install-deps
        - ruby/rspec-test
  workflows:
    version: 2
    build_analyze_and_test:
        jobs:
          - build
          - analyze:
              requires:
                - build
          - test:
              requires:
                - build
