---
  version: 2.1
  orbs:
    ruby: circleci/ruby@0.1.2
  jobs:
    build:
      docker:
        - image: circleci/ruby:2.7.0
          environment:
            RAILS_ENV: test
      steps:
        - checkout
        - run:
            name: Which bundler?
            command: bundle -v
        - ruby/bundle-install
    test:
      docker:
        - image: circleci/ruby:2.7.0
          environment:
            RAILS_ENV: test
      steps:
        - checkout
        - run:
            name: Which bundler?
            command: bundle -v
        - ruby/bundle-install
        - run:
            name: Run RSpec
            command: bundle exec rspec
  workflows:
    version: 2
    build_and_test:
        jobs:
          - build
          - test:
              requires:
                - build
